ALTER TABLE IF EXISTS accounts 
DROP CONSTRAINT accounts_owner_fkey;

ALTER TABLE  IF EXISTS accounts 
DROP CONSTRAINT owner_currency_key;

ALTER TABLE IF EXISTS accounts 
ALTER COLUMN owner TYPE VARCHAR USING owner::VARCHAR;

DROP TABLE IF EXISTS users;
